update: scripts

diff --git a/scripts/.local/bin/microphone b/scripts/.local/bin/microphone
--- a/scripts/.local/bin/microphone
+++ b/scripts/.local/bin/microphone
@@ -1,30 +1,28 @@
 #!/bin/sh
 
-arg=$1
-togglemute=0
-
-case $arg in
+case $1 in
 -m | --mute)
-	togglemute=1
-	;;
+  pactl set-source-mute @DEFAULT_SOURCE@ 1
+  exit 0
+  ;;
+-u | --unmute)
+  pactl set-source-mute @DEFAULT_SOURCE@ 0
+  exit 0
+  ;;
+-t | --toggle)
+  pactl set-source-mute @DEFAULT_SOURCE@ toggle
+  exit 0
+  ;;
 -s | --status)
-	s=$(pactl get-source-mute @DEFAULT_SOURCE@ | sed 's/Mute: //')
-	if [ "$s" == "yes" ]; then
-		echo "OFF"
-	else
-		echo "ON"
-	fi
-	;;
+  s=$(pactl get-source-mute @DEFAULT_SOURCE@ | sed 's/Mute: //')
+  if [ "$s" == "yes" ]; then
+    echo "OFF"
+  else
+    echo "ON"
+  fi
+  ;;
 *)
-	echo "Invalid option" >&2
-	exit 1
-	;;
+  echo "Invalid option" >&2
+  exit 1
+  ;;
 esac
-
-if [ $togglemute == 1 ]; then
-	pactl set-source-mute @DEFAULT_SOURCE@ toggle
-	exit 0
-fi
-
-echo "Invalid option" >&2
-exit 1
diff --git a/scripts/.local/bin/toggle_touchpad b/scripts/.local/bin/toggle_touchpad
--- a/scripts/.local/bin/toggle_touchpad
+++ b/scripts/.local/bin/toggle_touchpad
@@ -3,10 +3,30 @@
 TOUCHPAD_ID=$(xinput list | grep -i Touchpad | sed 's/.*id=\(.*\) *\[.*/\1/')
 TOUCHPAD_ENABLED=$(xinput list-props $TOUCHPAD_ID | grep -i "Device Enabled" | sed 's/.*\(.\)$/\1/')
 
-if [ $TOUCHPAD_ENABLED -eq 1 ]; then
-	notify-send -u normal -t 1500 "Disabling touchpad"
-	xinput disable $TOUCHPAD_ID
-else
-	notify-send -u normal -t 1500 "Enabling touchpad"
-	xinput enable $TOUCHPAD_ID
+if [ -z "$1" ]; then
+  if [ $TOUCHPAD_ENABLED -eq 1 ]; then
+    notify-send -u normal -t 1500 "Disabling touchpad"
+    xinput disable $TOUCHPAD_ID
+  else
+    notify-send -u normal -t 1500 "Enabling touchpad"
+    xinput enable $TOUCHPAD_ID
+  fi
+  exit 0
 fi
+
+case $1 in
+--on)
+  notify-send -u normal -t 1500 "Enabling touchpad"
+  xinput enable $TOUCHPAD_ID
+  exit 0
+  ;;
+--off)
+  notify-send -u normal -t 1500 "Disabling touchpad"
+  xinput disable $TOUCHPAD_ID
+  exit 0
+  ;;
+*)
+  echo "Invalid option" >&2
+  exit 1
+  ;;
+esac
diff --git a/scripts/.local/bin/toggle_wifi b/scripts/.local/bin/toggle_wifi
--- a/scripts/.local/bin/toggle_wifi
+++ b/scripts/.local/bin/toggle_wifi
@@ -2,10 +2,30 @@
 
 connected=$(nmcli -fields WIFI g)
 
-if [[ "$connected" =~ "enabled" ]]; then
-  nmcli radio wifi off
-  notify-send -t 2000 "WIFI disconnected"
-elif [[ "$connected" =~ "disabled" ]]; then
+if [ -z "$1" ]; then
+  if [[ "$connected" =~ "enabled" ]]; then
+    nmcli radio wifi off
+    notify-send -t 2000 "WIFI disconnected"
+  elif [[ "$connected" =~ "disabled" ]]; then
+    nmcli radio wifi on
+    notify-send -t 2000 "WIFI connected"
+  fi
+  exit 0
+fi
+
+case $1 in
+--on)
   nmcli radio wifi on
   notify-send -t 2000 "WIFI connected"
-fi
+  exit 0
+  ;;
+--off)
+  nmcli radio wifi off
+  notify-send -t 2000 "WIFI disconnected"
+  exit 0
+  ;;
+*)
+  echo "Invalid option" >&2
+  exit 1
+  ;;
+esac
