update: scripts

diff --git a/scripts/.local/bin/set_light b/scripts/.local/bin/set_light
--- a/scripts/.local/bin/set_light
+++ b/scripts/.local/bin/set_light
@@ -1,30 +1,30 @@
-#!/bin/bash
+#!/bin/sh
 
 arg=$1
 lightup=0
 lightdown=0
 
 case $arg in
-  -u | --up)
-    lightup=1
-    ;;
-  -d | --down)
-    lightdown=1
-    ;;
-  *)
-    echo "Invalid option" >&2
-    exit 1
-    ;;
+-u | --up)
+	lightup=1
+	;;
+-d | --down)
+	lightdown=1
+	;;
+*)
+	echo "Invalid option" >&2
+	exit 1
+	;;
 esac
 
 if [ $lightup == 1 ]; then
-  light -A 12 && light -O && brightness &
-  exit 0
+	light -A 12 && light -O && brightness &
+	exit 0
 fi
 
 if [ $lightdown == 1 ]; then
-  light -U 12 && light -O && brightness &
-  exit 0
+	light -U 12 && light -O && brightness &
+	exit 0
 fi
 
 echo "Invalid option" >&2
diff --git a/scripts/.local/bin/volume b/scripts/.local/bin/volume
--- a/scripts/.local/bin/volume
+++ b/scripts/.local/bin/volume
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 
 arg=$1
 volup=0
@@ -6,34 +6,34 @@ voldown=0
 volmute=0
 
 case $arg in
-  -u | --up)
-    volup=1
-    ;;
-  -d | --down)
-    voldown=1
-    ;;
-  -m | --mute)
-    volmute=1
-    ;;
-  *)
-    echo "Invalid option" >&2
-    exit 1
-    ;;
+-u | --up)
+	volup=1
+	;;
+-d | --down)
+	voldown=1
+	;;
+-m | --mute)
+	volmute=1
+	;;
+*)
+	echo "Invalid option" >&2
+	exit 1
+	;;
 esac
 
 if [ $volup == 1 ]; then
-  pactl set-sink-volume @DEFAULT_SINK@ +5%
-  exit 0
+	pactl set-sink-volume @DEFAULT_SINK@ +5%
+	exit 0
 fi
 
 if [ $voldown == 1 ]; then
-  pactl set-sink-volume @DEFAULT_SINK@ -5%
-  exit 0
+	pactl set-sink-volume @DEFAULT_SINK@ -5%
+	exit 0
 fi
 
 if [ $volmute == 1 ]; then
-  pactl set-sink-mute @DEFAULT_SINK@ toggle
-  exit 0
+	pactl set-sink-mute @DEFAULT_SINK@ toggle
+	exit 0
 fi
 
 echo "Invalid option" >&2
