feat: add default value feature to update_music script

diff --git a/scripts/.local/bin/update_music b/scripts/.local/bin/update_music
--- a/scripts/.local/bin/update_music
+++ b/scripts/.local/bin/update_music
@@ -3,42 +3,42 @@
 declare -A musicExtensions=([mp3]=1 [flac]=1)
 
 function editMusicTags() {
-  oldDirectory=$1
-  newDirectory=$2
-  filename=$3
-  artist=$4
-  album=$5
-  year=$6
+	oldDirectory=$1
+	newDirectory=$2
+	filename=$3
+	artist=$4
+	album=$5
+	year=$6
 
-  ## FIX : Performer tag doesn't work
-  ffmpeg -i "$oldDirectory/$filename" \
-    -codec copy \
-    -metadata performer="" \
-    -metadata composer="" \
-    -metadata genre="" \
-    -metadata description="" \
-    -metadata disc="0" \
-    -metadata publisher="" \
-    -metadata copyright="" \
-    -metadata comment="" \
-    -metadata publisher="" \
-    -metadata author="$artist" \
-    -metadata artist="$artist" \
-    -metadata album_artist="$artist" \
-    -metadata album="$album" \
-    -metadata date="$year" \
-    -y "$newDirectory/$filename"
+	## FIX : Performer tag doesn't work
+	ffmpeg -i "$oldDirectory/$filename" \
+		-codec copy \
+		-metadata performer="" \
+		-metadata composer="" \
+		-metadata genre="" \
+		-metadata description="" \
+		-metadata disc="0" \
+		-metadata publisher="" \
+		-metadata copyright="" \
+		-metadata comment="" \
+		-metadata publisher="" \
+		-metadata author="$artist" \
+		-metadata artist="$artist" \
+		-metadata album_artist="$artist" \
+		-metadata album="$album" \
+		-metadata date="$year" \
+		-y "$newDirectory/$filename"
 }
 
 inputAlbumDirectory=$1
 
 # Checking that every file within the folder is music
 for file in "$inputAlbumDirectory"/*; do
-  ext="${file##*.}"
-  if ! [[ ${musicExtensions["$ext"]} ]]; then
-    echo "Error: the folder has unwanted files, please make sure that every file inside the folder are mp3 or flac"
-    exit 1
-  fi
+	ext="${file##*.}"
+	if ! [[ ${musicExtensions["$ext"]} ]]; then
+		echo "Error: the folder has unwanted files, please make sure that every file inside the folder are mp3 or flac"
+		exit 1
+	fi
 done
 
 firstFilePath=$(find "$inputAlbumDirectory" -maxdepth 1 -type f | head -n 1)
@@ -48,24 +48,24 @@ defaultAlbum=$(ffprobe -v error -select_streams a:0 -show_entries format_tags=al
 defaultArtist=$(ffprobe -v error -select_streams a:0 -show_entries format_tags=artist -of default=noprint_wrappers=1:nokey=1 "$firstFilePath")
 defaultYear=$(ffprobe -v error -select_streams a:0 -show_entries format_tags=date -of default=noprint_wrappers=1:nokey=1 "$firstFilePath" | sed 's/-.*//')
 
-read -e -p "Please enter the artist name : " -i "" artist
-read -e -p "Please enter the album name : " -i "" album
-read -e -p "Please enter the year : " -i "" year
+read -e -p "Please enter the artist name : (Current: artist -> $defaultArtist | album artist -> $defaultAlbumArtist) " -i "" artist
+read -e -p "Please enter the album name : (Current: $defaultAlbum) " -i "" album
+read -e -p "Please enter the year : (Current: $defaultYear) " -i "" year
 
 if ! [ -n "$artist" ]; then
-  if [ -n "$defaultAlbumArtist" ]; then
-    artist=$defaultAlbumArtist
-  else
-    artist=$defaultArtist
-  fi
+	if [ -n "$defaultAlbumArtist" ]; then
+		artist=$defaultAlbumArtist
+	else
+		artist=$defaultArtist
+	fi
 fi
 
 if ! [ -n "$album" ]; then
-  album=$defaultAlbum
+	album=$defaultAlbum
 fi
 
 if ! [ -n "$year" ]; then
-  year=$defaultYear
+	year=$defaultYear
 fi
 
 newAlbumDirectory="$HOME/music/$artist-($year)-$album"
@@ -73,7 +73,7 @@ newAlbumDirectory="$HOME/music/$artist-($year)-$album"
 mkdir "$newAlbumDirectory"
 
 for file in "$inputAlbumDirectory"/*; do
-  editMusicTags "$inputAlbumDirectory" "$newAlbumDirectory" "${file##*/}" "$artist" "$album" "$year"
+	editMusicTags "$inputAlbumDirectory" "$newAlbumDirectory" "${file##*/}" "$artist" "$album" "$year"
 done
 
 mv "$inputAlbumDirectory" "$inputAlbumDirectory (done)"
