fix: wallpaper script   -Added auto reload   -Added scaling mode

diff --git a/scripts/.local/bin/wallpaper b/scripts/.local/bin/wallpaper
--- a/scripts/.local/bin/wallpaper
+++ b/scripts/.local/bin/wallpaper
@@ -3,157 +3,193 @@
 WALLPAPERS_DIR="$HOME/pictures/wallpapers/walls"
 LOCKSCREENS_DIR="$HOME/pictures/wallpapers/lockscreens"
 I3CONFIG_PATH="$XDG_CONFIG_HOME/i3"
+LOCKSCREEN_SCRIPT_PATH="$HOME/.dotfiles/scripts/.local/bin"
 
 # converts an image to jpg and moves it into WALLPAPERS directory
 add_wall_image() {
-	image_path=$1
-	new_image_name=$2
+  image_path=$1
+  new_image_name=$2
 
-	if [ ! -f "$image_path" ]; then
-		echo "Error: File doesn't exists."
-		exit 1
-	fi
+  if [ ! -f "$image_path" ]; then
+    echo "Error: File doesn't exists."
+    exit 1
+  fi
 
-	extension=${image_path##*.}
-	mimetype=$(file -b --mime-type "$image_path" | sed 's/\/.*//g')
+  extension=${image_path##*.}
+  mimetype=$(file -b --mime-type "$image_path" | sed 's/\/.*//g')
 
-	if [ "$mimetype" != "image" ]; then
-		echo "Error: Selected file is not an image."
-		exit 1
-	fi
+  if [ "$mimetype" != "image" ]; then
+    echo "Error: Selected file is not an image."
+    exit 1
+  fi
 
-	if [ "$extension" = "jpg" ]; then
-		echo "Copying image into wallpapers directory..."
-		cp "$image_path" "$WALLPAPERS_DIR/$new_image_name.jpg"
-		echo "Wallpaper image is moved into wallpapers directory successfully."
-	else
-		echo "File is not jpg, converting to jpg..."
-		ffmpeg -i "$image_path" "$WALLPAPERS_DIR/$new_image_name.jpg" -loglevel error
-		echo "Wallpaper image converted into jpg, and moved into wallpapers directory successfully."
-	fi
+  if [ "$extension" = "jpg" ]; then
+    echo "Copying image into wallpapers directory..."
+    cp "$image_path" "$WALLPAPERS_DIR/$new_image_name.jpg"
+    echo "Wallpaper image is moved into wallpapers directory successfully."
+  else
+    echo "File is not jpg, converting to jpg..."
+    ffmpeg -i "$image_path" "$WALLPAPERS_DIR/$new_image_name.jpg" -loglevel error
+    echo "Wallpaper image converted into jpg, and moved into wallpapers directory successfully."
+  fi
 }
 
 # selects an image inside WALLPAPERS directory and creates a lockscreen image based on it
 create_lockscreen_image() {
-	image_name=$1
-	silent_flag=$2
-	image_path=$WALLPAPERS_DIR/$image_name
+  image_name=$1
+  silent_flag=$2
+  image_path=$WALLPAPERS_DIR/$image_name
 
-	if [ ! -f "$image_path" ]; then
-		echo "Error: Wallpaper with name: $image_name doesn't exists inside wallpapers directory."
-		exit 1
-	fi
+  if [ ! -f "$image_path" ]; then
+    echo "Error: Wallpaper with name: $image_name doesn't exists inside wallpapers directory."
+    exit 1
+  fi
 
-	extension=${image_path##*.}
-	mimetype=$(file -b --mime-type "$image_path" | sed 's/\/.*//g')
+  extension=${image_path##*.}
+  mimetype=$(file -b --mime-type "$image_path" | sed 's/\/.*//g')
 
-	if [ "$mimetype" != "image" ] || [ "$extension" != "jpg" ]; then
-		echo "Error: Selected file $image_name is not an image or is not jpg."
-		exit 1
-	fi
+  if [ "$mimetype" != "image" ] || [ "$extension" != "jpg" ]; then
+    echo "Error: Selected file $image_name is not an image or is not jpg."
+    exit 1
+  fi
 
-	image_basename=${image_name%.*}
+  image_basename=${image_name%.*}
 
-	lockscreen_path=$LOCKSCREENS_DIR/$image_basename.png
+  lockscreen_path=$LOCKSCREENS_DIR/$image_basename.png
 
-	if [ -f "$lockscreen_path" ]; then
-		[ "$silent_flag" -eq 0 ] && echo "Lockscreen of image $image_name already exists."
-	else
-		[ "$silent_flag" -eq 0 ] && echo "Creating lockscreen image..."
-		ffmpeg -i "$image_path" -vf "scale=1920:1080, boxblur=15" "$lockscreen_path" -loglevel error
-		[ "$silent_flag" -eq 0 ] && echo "Lockscreen image of $image_name has been created successfully."
-	fi
+  if [ -f "$lockscreen_path" ]; then
+    [ "$silent_flag" -eq 0 ] && echo "Lockscreen of image $image_name already exists."
+  else
+    [ "$silent_flag" -eq 0 ] && echo "Creating lockscreen image..."
+    ffmpeg -i "$image_path" -vf "scale=1920:1080, boxblur=15" "$lockscreen_path" -loglevel error
+    [ "$silent_flag" -eq 0 ] && echo "Lockscreen image of $image_name has been created successfully."
+  fi
 }
 
 # creates lockscreen image with all the images inside the WALLPAPERS directory
 # (if there is not a lockscreen image exists)
 set_all_lockscreens() {
-	echo "Creating lockscreen image for all wallpapers..."
+  echo "Creating lockscreen image for all wallpapers..."
 
-	for file in "$WALLPAPERS_DIR"/*; do
+  for file in "$WALLPAPERS_DIR"/*; do
 
-		if [ -f "$file" ]; then
-			file_name=${file##*/}
-			create_lockscreen_image "$file_name" 1
-		fi
-	done
+    if [ -f "$file" ]; then
+      file_name=${file##*/}
+      create_lockscreen_image "$file_name" 1
+    fi
+  done
 
-	echo "Lockscreen images have been created successfully."
+  echo "Lockscreen images have been created successfully."
 }
 
 # sets the i3 background variable name
 set_i3_background() {
-	image_name=$1
-	image_path=$WALLPAPERS_DIR/$image_name.jpg
+  image_name=$1
+  image_path=$WALLPAPERS_DIR/$image_name.jpg
 
-	if [ ! -f "$image_path" ]; then
-		echo "Error: Wallpaper with name: $image_name.jpg doesn't exists inside wallpapers directory."
-		exit 1
-	fi
+  if [ ! -f "$image_path" ]; then
+    echo "Error: Wallpaper with name: $image_name.jpg doesn't exists inside wallpapers directory."
+    exit 1
+  fi
 
-	extension=${image_path##*.}
-	mimetype=$(file -b --mime-type "$image_path" | sed 's/\/.*//g')
+  extension=${image_path##*.}
+  mimetype=$(file -b --mime-type "$image_path" | sed 's/\/.*//g')
 
-	if [ "$mimetype" != "image" ] || [ "$extension" != "jpg" ]; then
-		echo "Error: Selected file $image_name is not an image or is not jpg."
-		exit 1
-	fi
+  if [ "$mimetype" != "image" ] || [ "$extension" != "jpg" ]; then
+    echo "Error: Selected file $image_name is not an image or is not jpg."
+    exit 1
+  fi
 
-	i3_config_file_path=$I3CONFIG_PATH/config
+  i3_config_file_path=$I3CONFIG_PATH/config
+  lockscreen_script=$LOCKSCREEN_SCRIPT_PATH/start_xss_lock
+  image_bg_mode=$(cat $i3_config_file_path | grep "bgmode" | sed 's/.*\(\".*\"\)/\1/' | sed 's/\"//g')
 
-	grep bgname "$i3_config_file_path" | sed -i "/set \$bgname/s/\"[^\"]*\"/\"$image_name\"/" "$i3_config_file_path"
+  grep bgname "$i3_config_file_path" | sed -i "/set \$bgname/s/\"[^\"]*\"/\"$image_name\"/" "$i3_config_file_path"
+  sed -i "s/BGNAME=.*/\BGNAME=\"$image_name\"/" "$lockscreen_script"
 
-	echo "I3 config updated."
-	echo "Please restart your i3 to change the wallpaper."
+  echo "I3 config updated."
+  feh --no-fehbg $image_bg_mode "$image_path"
+  i3 reload &> /dev/null
+  pkill xss-lock
+  start_xss_lock &
+  echo "Wallpaper updated successfully."
+}
+
+# sets the i3 background mode
+set_i3_background_mode() {
+  image_bg_mode=$1
+
+  if [ "$image_bg_mode" != "center" ] && [ $image_bg_mode != "max" ] && [ $image_bg_mode != "tile" ] && [ $image_bg_mode != "fill" ]; then
+    echo "Error: Wrong option"
+    exit 1
+  fi
+
+  i3_config_file_path=$I3CONFIG_PATH/config
+  image_bg_name=$(cat $i3_config_file_path | grep "bgname" | sed 's/.*\(\".*\"\)/\1/' | sed 's/\"//g')
+  image_path=$WALLPAPERS_DIR/$image_bg_name.jpg
+
+  grep bgmode "$i3_config_file_path" | sed -i "/set \$bgmode/s/\"[^\"]*\"/\"--bg-$image_bg_mode\"/" "$i3_config_file_path"
+
+  echo "I3 config updated."
+  feh --no-fehbg --bg-$image_bg_mode "$image_path"
+  i3 reload &> /dev/null
+  echo "Wallpaper updated successfully."
 }
 
 first_arg=$1
 
 case $first_arg in
 "--add-wall" | "-a")
-	file_name=$2
-	file_path=$PWD/$file_name
-	printf "Enter wallpaper name: "
-	read -r wall_name
+  file_name=$2
+  file_path=$PWD/$file_name
+  printf "Enter wallpaper name: "
+  read -r wall_name
 
-	add_wall_image "$file_path" "$wall_name"
-	create_lockscreen_image "$wall_name.jpg" 0
+  add_wall_image "$file_path" "$wall_name"
+  create_lockscreen_image "$wall_name.jpg" 0
 
-	printf "You want to set the wallpaper? [y/n] "
-	read -r ans
+  printf "You want to set the wallpaper? [y/n] "
+  read -r ans
 
-	if [ "$ans" = "y" ]; then
-		set_i3_background "$wall_name"
-	else
-		echo "Wallpaper has been added, now you can set it by running: "
-		echo "wallpaper --set-wall $wall_name"
-	fi
+  if [ "$ans" = "y" ]; then
+    set_i3_background "$wall_name"
+  else
+    echo "Wallpaper has been added, now you can set it by running: "
+    echo "wallpaper --set-wall $wall_name"
+  fi
 
-	exit 0
-	;;
+  exit 0
+  ;;
 "--create-lockscreen" | "-cl")
-	file_name=$2
+  file_name=$2
 
-	create_lockscreen_image "$file_name" 0
-	exit 0
-	;;
+  create_lockscreen_image "$file_name" 0
+  exit 0
+  ;;
 "--set-lockscreens" | "-sl")
-	printf "Are you sure that you want to set all the lockscreen images? [y/n] "
-	read -r ans
+  printf "Are you sure that you want to set all the lockscreen images? [y/n] "
+  read -r ans
 
-	if [ "$ans" = "y" ]; then
-		set_all_lockscreens
-	fi
+  if [ "$ans" = "y" ]; then
+    set_all_lockscreens
+  fi
 
-	exit 1
-	;;
+  exit 1
+  ;;
 "--set-wall" | "-sw")
-	wall_name=$2
+  wall_name=$2
 
-	set_i3_background "$wall_name"
+  set_i3_background "$wall_name"
 
-	exit 0
-	;;
+  exit 0
+  ;;
+"--set-mode" | "-sm")
+  wall_mode=$2
+
+  set_i3_background_mode "$wall_mode"
+
+  exit 0
+  ;;
 esac
 
 echo "Error: Invalid argument"
@@ -199,4 +235,15 @@ Valid commands:
 
     For adding an image outside
     the wallpapers dir, simply use --add-wall
+
+  5.
+    --set-mode mode
+    -sm mode 
+
+    For setting a scaling mode for wallpaper.
+    Options are:
+      tile
+      center
+      max
+      fill
 "
